---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-provider-helm
  namespace: crossplane-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-provider-helm
subjects:
  - kind: ServiceAccount
    name: crossplane-provider-helm
    namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: crossplane-provider-helm
spec:
  serviceAccountTemplate:
    metadata:
      name: crossplane-provider-helm
  deploymentTemplate:
    spec:
      selector:
        matchLabels:
          app: crossplane-provider-helm
      template:
        metadata:
          labels:
            app: crossplane-provider-helm
        spec:
          containers:
            - name: package-runtime
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.17.0
  runtimeConfigRef:
    name: crossplane-provider-helm
